### ISSUE TITLE
Custom Regular Expression

### ISSUE THREAD

**Issue by donniefitz2** [pridees/combine-validate#3]
I'm having a hard time understanding how to validate using a custom regex string. I see the enum of various types of pre-set expressions, but how does one validate for something outside of those definitions? If I try to pass a string as the regex, I get an error that the string does not conform to the RegularPattern protocol.

**Comment by pridees** [comment]
Hi @donniefitz2 

Thank you for your question.

I left the custom regex example in the Sources/Examples folder. Follow this [here](https://github.com/pridees/combine-validate/blob/main/Sources/Examples/FlexTextFieldVlidation.swift)

Custom regex should be conform to RegexProtocol in order to have more convenient underlying API in short code, instead of using complex Regex third party libs.

By design custom regex ease to construct and look like that:

```swift
enum SocialLinkPattern: RegexPattern, RegexProtocol {
    case facebook = #"(?:https?:\/\/)?(?:www\.)?facebook\.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[\w\-]*\/)*?(\/)?([\w\-\.]{5,})"#
    case linkedIn = #"^(http(s)?:\/\/)?([\w]+\.)?linkedin\.com\/(pub|in|profile)"#
    case instagram = #"(?:(?:http|https):\/\/)?(?:www.)?(?:instagram.com|instagr.am|instagr.com)\/(\w+)"#
}
```

Hope I help to you.

Have a nice day!

**Comment by donniefitz2** [comment]
Okay, I see what you mean. I'll create my own implementation of RegexPattern. Thanks for the quick response and for the library.
